export const sampleData = {
  id: 1,
  user_id: '98d1608d-7204-43bb-b636-fca416753a9d',
  individual_client_group_id: 1,
  first_name: 'Nickolas',
  middle_name: 'Mueller',
  last_name: 'Eichmann',
  email: 'jacobs.blaze@corkery.com',
  address: 'Jerelchester',
  state: 'Delaware',
  country: 'Angola',
  post_code: '09407',
  dob: '1996-03-31T00:00:00.000000Z',
  gender: 'Female',
  // is_primary_entity: 1,
  // is_existing_client: 1,
  // is_au_resident: 1,
  // is_dependent: 1,
  // is_risk_taker: 1,
  // is_asset_holder: 1,
  is_primary_entity: true,
  is_existing_client: true,
  is_au_resident: true,
  is_dependent: true,
  is_risk_taker: true,
  is_asset_holder: true,
  created_by: '',
  updated_by: null,
  created_at: '2023-03-31T08:12:49.000000Z',
  updated_at: '2023-03-31T08:12:49.000000Z',
  // is_key_person: '1',
  is_key_person: true,
  street: '35768 Soledad Walk Suite 311',
  suburb: 'Abshire Ports',
  city: 'South Helenechester',
  existing_client: 'Jordon Dooley',
  retirement_age: 60,
  notes_by_user:
    'Quod et molestiae qui eligendi quaerat veniam officiis. Aliquid voluptatem ab dicta quasi ut id quidem sit. Laudantium consectetur illum consequuntur quia eius.',
  // is_family_member: null,
  is_family_member: false,
  // NOTE: Properties below are not yet implemented and for testing purposes only!
  risk_type: 'Asset Holder',
  marital_status: 'single',
  relationship_type: 'son',
  family_relationship_type: 'son',
  related_entity: 'Jennie Kim',
  asset_liabilities_profile: 'good',
};
